services:
  speedtest-tracker:
    container_name: speedtest-tracker
    ports:
      - 8083:80
      # - '8443:443'
    environment:
      - PUID=1000
      - PGID=1000
      - DB_CONNECTION=pgsql
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - APP_NAME="Speedtest Tracker"
      - APP_ENV=production
      - APP_KEY=${APP_KEY}
      - APP_DEBUG=false
      - APP_URL=https://speedtest.local.timmybtech.com/
      - SPEEDTEST_SCHEDULE=0 */12 * * *
      - SPEEDTEST_INTERNET_CHECK_HOSTNAME=https://google.com
    volumes:
      - ./config:/config
      - ./web:/etc/ssl/web
    image: ghcr.io/linuxserver/speedtest-tracker:1.13.2-ls129
    restart: unless-stopped
    labels:
      io.containers.autoupdate: "registry" # for use with podman
