---
services:
  it-tools:
    image: docker.io/corentinth/it-tools:latest
    container_name: it-tools
    ports:
      - "5884:80"
    restart: unless-stopped
    labels:
      io.containers.autoupdate: "registry"
