---
services:
  proxmox-exporter:
    image: docker.io/prompve/prometheus-pve-exporter:3.7.0
    container_name: proxmox-exporter
    volumes:
      - "./pve.yml:/etc/prometheus/pve.yml"
    ports:
      - "9221:9221"
    init: true
    labels:
      io.containers.autoupdate: "registry"
