---
services:
  dozzle:
    container_name: dozzle
    image: docker.io/amir20/dozzle:v9.0.1
    security_opt:
      - apparmor:unconfined
      - "label=type:container_runtime_t" # for podman use
    volumes:
      - /run/user/1000/podman/podman.sock:/var/run/docker.sock:z # for podman use
    environment:
      - DOZZLE_REMOTE_AGENT=${DOZZLE_AGENTS}
      - DOZZLE_HOSTNAME=${HOSTNAME}
    ports:
      - 9999:8080
    restart: unless-stopped
    labels:
      io.containers.autoupdate: "registry"
