---
services:
  mysqld-exporter:
    network_mode: host
    environment:
      - "MYSQLD_EXPORTER_PASSWORD=${MYSQLD_EXPORTER_PASSWORD}"
    image: prom/mysqld-exporter
    container_name: mysqld_exporter
    restart: unless-stopped
    command: "--mysqld.address=${MYSQLD_EXPORTER_HOST}:3306 --mysqld.username=${MYSQLD_EXPORTER_USERNAME} "
