---
services:
  dockhand:
    image: docker.io/fnsys/dockhand:4163738c
    container_name: dockhand
    restart: unless-stopped
    userns_mode: "keep-id"
    ports:
      - "3007:3000"
    volumes:
      - /run/user/${USER_ID-1000}/podman/podman.sock:/var/run/docker.sock:z
      - dockhand_data:/app/data

volumes:
  dockhand_data:
