---
services:
  node-bootstrap: # optional, local themes and icons
    image: docker.io/aceberg/node-bootstrap
    restart: unless-stopped
    ports:
      - 8850:8850
  anyappstart:
    image: docker.io/aceberg/anyappstart # dockerhub
    restart: unless-stopped
    ports:
      - 8855:8855
    volumes:
      - ./.dockerdata/AnyAppStart:/data/AnyAppStart
      - /run/user/${USER_ID-1000}/podman/podman.sock:/var/run/docker.sock:z
    command: "-n http://node-bootstrap:8850"
    environment:
      TZ: America/New_York # required, default: ""
      # NODEPATH: "http://YOUR-ADDRESS:8850" # optional, default: ""
      # HOST: "0.0.0.0"         # optional, default: 0.0.0.0
      # PORT: "8855"            # optional, default: 8855
      THEME: "minty" # optional, default: minty
      COLOR: "dark" # optional, default: dark
