version: "3.5"

services:
  diun:
    image: docker.io/crazymax/diun:4.29
    container_name: diun
    command: serve
    volumes:
      - "./data:/data"
      - "./diun.yml:/diun.yml:ro"
      - "./custom-images.yml:/custom-images.yml:ro"

      # docker mode
      # - "/var/run/docker.sock:/var/run/docker.sock"

      # root mode
      # - "/run/podman/podman.sock:/var/run/docker.sock"

      # rootless mode
      - "$XDG_RUNTIME_DIR/podman/podman.sock:/var/run/docker.sock"
      - "/run/user/1000/podman/podman.sock:/var/run/docker.sock"
    environment:
      - "TZ=America/New_York"
      - "LOG_LEVEL=info"
      - "LOG_JSON=false"
    labels:
      - "diun.enable=true"
