---
services:
  pulse:
    image: docker.io/rcourtman/pulse:v5.0.0-rc.3
    container_name: pulse
    ports:
      - "7655:7655"
    volumes:
      - pulse_data:/data
    environment:
      - TZ=America/New_York
      - ALLOWED_ORIGINS=https://pulse.local.timmybtech.com
    restart: unless-stopped
    # healthcheck:
    #   test:
    #     [
    #       "CMD",
    #       "wget",
    #       "--no-verbose",
    #       "--tries=1",
    #       "--spider",
    #       "http://localhost:7655",
    #     ]
    #   interval: 30s
    #   timeout: 10s
    #   retries: 3
    #   start_period: 30s
    labels:
      io.containers.autoupdate: "registry"

volumes:
  pulse_data:
    driver: local
