---
services:
  pgweb:
    container_name: pgweb
    restart: always
    image: docker.io/sosedoff/pgweb:0.17.0
    ports:
      - "8084:8081"
    environment:
      - PGWEB_DATABASE_URL=${DATABASE_URL}
    labels:
      io.containers.autoupdate: "registry"
