services:
  dozzle-agent:
    image: docker.io/amir20/dozzle:v9.0.2
    container_name: dozzle-agent
    command: agent
    volumes:
      - /run/user/${USER_ID}/podman/podman.sock:/var/run/docker.sock:z
    # needed only for homelab-oci03 to work
    security_opt:
      - apparmor:unconfined
      - "label=type:container_runtime_t"
    environment:
      - DOZZLE_HOSTNAME=${HOSTNAME}
    ports:
      - 7007:7007
    labels:
      io.containers.autoupdate: "registry"
