---
version: "3.1"

services:
  uptime-kuma:
    image: docker.io/louislam/uptime-kuma:2.0.2
    container_name: uptime-kuma
    volumes:
      - ./data:/app/data:Z
    #    ports:
    #      - 3001:3001
    restart: unless-stopped
    # for oci
    # security_opt:
    #   - no-new-privileges:true
    network_mode: "host"
    labels:
      io.containers.autoupdate: "registry"
