---
services:
  cupdate:
    image: ghcr.io/alexgustafsson/cupdate:0.23.0
    container_name: cupdate
    ports:
      - "8082:8080"
    environment:
      - "CUPDATE_DOCKER_HOST=unix:///var/run/podman.sock"
    volumes:
      - "/run/user/1000/podman/podman.sock:/var/run/podman.sock:ro"
    tty: true
    stdin_open: true
