---
volumes:
  prometheus_data:
    external: true

services:
  prometheus:
    image: docker.io/prom/prometheus:v3.8.1
    container_name: prometheus
    user: "root"
    volumes:
      - "./prometheus.yml:/etc/prometheus/prometheus.yml"
      - "prometheus_data:/prometheus"
    restart: unless-stopped
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    labels:
      io.containers.autoupdate: "registry"
    network_mode: host
