services:
  your-spotify-server:
    image: docker.io/yooooomi/your_spotify_server
    restart: always
    container_name: your-spotify-server
    ports:
      - "8086:8080"
    environment:
      API_ENDPOINT: http://192.168.86.174:8086 # This MUST be included as a valid URL in the spotify dashboard (see below)
      CLIENT_ENDPOINT: http://192.168.86.174:3003
      SPOTIFY_PUBLIC: ${SPOTIFY_CLIENT_ID}
      SPOTIFY_SECRET: ${SPOTIFY_CLIENT_SECRET}
      MONGO_ENDPOINT: ${MONGO_ENDPOINT}
      CORS: http://192.168.86.174:3003
    labels:
      io.containers.autoupdate: "registry"
