---
services:
  nutalert:
    # Using the SHA of the image did not seem to work
    image: ghcr.io/rmfatemi/nutalert:latest
    container_name: nutalert
    network_mode: host
    volumes:
      - ./:/config
    restart: unless-stopped
