services:
  nutalert:
    image: ghcr.io/rmfatemi/nutalert:sha256-2f6d0c18526acd5c02bd5aa61caedf5aca16bb426c96dd30e921f90368daf7ff
    container_name: nutalert
    network_mode: host
    volumes:
      - ./:/config
    restart: unless-stopped
    healthcheck:
      disable: true
