services:
  semaphore:
    container_name: semaphore
    restart: unless-stopped
    ports:
      - 3005:3000
    image: docker.io/semaphoreui/semaphore:v2.16.46
    environment:
      SEMAPHORE_DB_USER: ${SEMAPHORE_DB_USER}
      SEMAPHORE_DB_PASS: ${SEMAPHORE_DB_PASS}
      SEMAPHORE_DB_HOST: ${SEMAPHORE_DB_HOST}
      SEMAPHORE_DB_PORT: ${SEMAPHORE_DB_PORT}
      SEMAPHORE_DB_DIALECT: postgres
      SEMAPHORE_DB: semaphore
      SEMAPHORE_PLAYBOOK_PATH: /tmp/semaphore/
      SEMAPHORE_ADMIN_PASSWORD: ${SEMAPHORE_ADMIN_PASSWORD}
      SEMAPHORE_ADMIN_NAME: ${SEMAPHORE_ADMIN_NAME}
      SEMAPHORE_ADMIN_EMAIL: ${SEMAPHORE_ADMIN_EMAIL}
      SEMAPHORE_ADMIN: ${SEMAPHORE_ADMIN}
      SEMAPHORE_ACCESS_KEY_ENCRYPTION: ${SEMAPHORE_ACCESS_KEY_ENCRYPTION}
      # if you wish to use ldap, set to: 'yes'
      SEMAPHORE_LDAP_ACTIVATED: "no"
    volumes:
      - /home/tbryant/.ssh/id_master_key_nopass:/home/semaphore/.ssh/id_master_key_nopass
      - ./config.json:/etc/semaphore/config.json
    labels:
      io.containers.autoupdate: "registry" # for use with podman
